"""empty message

Revision ID: 122a6ac9dade
Revises: 
Create Date: 2022-01-18 22:56:31.732277

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "122a6ac9dade"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Correlation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("x_data_type", sa.String(length=50), nullable=False),
        sa.Column("y_data_type", sa.String(length=50), nullable=False),
        sa.Column("correlation", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Correlation")
    # ### end Alembic commands ###
